<x-script.alpine.sidenav/>
<x-script.alpine.table.th/>
<x-script.alpine.form.ic/>
<x-script.alpine.form.seo/>
<x-script.alpine.form.date/>
<x-script.alpine.form.tags/>
<x-script.alpine.form.image/>
<x-script.alpine.form.title/>
<x-script.alpine.form.amount/>
<x-script.alpine.form.sortable/>
<x-script.alpine.form.richtext/>