<?php

namespace Jiannius\Atom\Services;

class Metadata
{
    public function countries($code = null) {
        $countries = [
            ["name" => "Afghanistan", "dial_code" => "+93", "iso_code" => "AF", "currency_code" => "AFN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/af.svg"],
            ["name" => "Aland Islands", "dial_code" => "+358", "iso_code" => "AX", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ax.svg"],
            ["name" => "Albania", "dial_code" => "+355", "iso_code" => "AL", "currency_code" => "ALL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/al.svg"],
            ["name" => "Algeria", "dial_code" => "+213", "iso_code" => "DZ", "currency_code" => "DZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/dz.svg"],
            ["name" => "American Samoa", "dial_code" => "+1684", "iso_code" => "AS", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/as.svg"],
            ["name" => "Andorra", "dial_code" => "+376", "iso_code" => "AD", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ad.svg"],
            ["name" => "Angola", "dial_code" => "+244", "iso_code" => "AO", "currency_code" => "AOA", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ao.svg"],
            ["name" => "Anguilla", "dial_code" => "+1264", "iso_code" => "AI", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ai.svg"],
            ["name" => "Antarctica", "dial_code" => "+672", "iso_code" => "AQ", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/aq.svg"],
            ["name" => "Antigua and Barbuda", "dial_code" => "+1268", "iso_code" => "AG", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ag.svg"],
            ["name" => "Argentina", "dial_code" => "+54", "iso_code" => "AR", "currency_code" => "ARS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ar.svg"],
            ["name" => "Armenia", "dial_code" => "+374", "iso_code" => "AM", "currency_code" => "AMD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/am.svg"],
            ["name" => "Aruba", "dial_code" => "+297", "iso_code" => "AW", "currency_code" => "AWG", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/aw.svg"],
            ["name" => "Ascension Island", "dial_code" => "+247", "iso_code" => "AC", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ac.svg"],
            ["name" => "Australia", "dial_code" => "+61", "iso_code" => "AU", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/au.svg"],
            ["name" => "Austria", "dial_code" => "+43", "iso_code" => "AT", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/at.svg"],
            ["name" => "Azerbaijan", "dial_code" => "+994", "iso_code" => "AZ", "currency_code" => "AZN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/az.svg"],
            ["name" => "Bahamas", "dial_code" => "+1242", "iso_code" => "BS", "currency_code" => "BSD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bs.svg"],
            ["name" => "Bahrain", "dial_code" => "+973", "iso_code" => "BH", "currency_code" => "BHD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bh.svg"],
            ["name" => "Bangladesh", "dial_code" => "+880", "iso_code" => "BD", "currency_code" => "BDT", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bd.svg"],
            ["name" => "Barbados", "dial_code" => "+1246", "iso_code" => "BB", "currency_code" => "BBD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bb.svg"],
            ["name" => "Belarus", "dial_code" => "+375", "iso_code" => "BY", "currency_code" => "BYR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/by.svg"],
            ["name" => "Belgium", "dial_code" => "+32", "iso_code" => "BE", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/be.svg"],
            ["name" => "Belize", "dial_code" => "+501", "iso_code" => "BZ", "currency_code" => "BZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bz.svg"],
            ["name" => "Benin", "dial_code" => "+229", "iso_code" => "BJ", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bj.svg"],
            ["name" => "Bermuda", "dial_code" => "+1441", "iso_code" => "BM", "currency_code" => "BMD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bm.svg"],
            ["name" => "Bhutan", "dial_code" => "+975", "iso_code" => "BT", "currency_code" => "BTN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bt.svg"],
            ["name" => "Bolivia", "dial_code" => "+591", "iso_code" => "BO", "currency_code" => "BOB", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bo.svg"],
            ["name" => "Bosnia and Herzegovina", "dial_code" => "+387", "iso_code" => "BA", "currency_code" => "BAM", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ba.svg"],
            ["name" => "Botswana", "dial_code" => "+267", "iso_code" => "BW", "currency_code" => "BWP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bw.svg"],
            ["name" => "Brazil", "dial_code" => "+55", "iso_code" => "BR", "currency_code" => "BRL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/br.svg"],
            ["name" => "British Indian Ocean Territory", "dial_code" => "+246", "iso_code" => "IO", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/io.svg"],
            ["name" => "Brunei Darussalam", "dial_code" => "+673", "iso_code" => "BN", "currency_code" => "BND", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bn.svg"],
            ["name" => "Bulgaria", "dial_code" => "+359", "iso_code" => "BG", "currency_code" => "BGN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bg.svg"],
            ["name" => "Burkina Faso", "dial_code" => "+226", "iso_code" => "BF", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bf.svg"],
            ["name" => "Burundi", "dial_code" => "+257", "iso_code" => "BI", "currency_code" => "BIF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bi.svg"],
            ["name" => "Cambodia", "dial_code" => "+855", "iso_code" => "KH", "currency_code" => "KHR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kh.svg"],
            ["name" => "Cameroon", "dial_code" => "+237", "iso_code" => "CM", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cm.svg"],
            ["name" => "Canada", "dial_code" => "+1", "iso_code" => "CA", "currency_code" => "CAD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ca.svg"],
            ["name" => "Cape Verde", "dial_code" => "+238", "iso_code" => "CV", "currency_code" => "CVE", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cv.svg"],
            ["name" => "Cayman Islands", "dial_code" => "+1345", "iso_code" => "KY", "currency_code" => "KYD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ky.svg"],
            ["name" => "Central African Republic", "dial_code" => "+236", "iso_code" => "CF", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cf.svg"],
            ["name" => "Chad", "dial_code" => "+235", "iso_code" => "TD", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/td.svg"],
            ["name" => "Chile", "dial_code" => "+56", "iso_code" => "CL", "currency_code" => "CLP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cl.svg"],
            ["name" => "China", "dial_code" => "+86", "iso_code" => "CN", "currency_code" => "CNY", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cn.svg"],
            ["name" => "Christmas Island", "dial_code" => "+61", "iso_code" => "CX", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cx.svg"],
            ["name" => "Cocos (Keeling) Islands", "dial_code" => "+61", "iso_code" => "CC", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cc.svg"],
            ["name" => "Colombia", "dial_code" => "+57", "iso_code" => "CO", "currency_code" => "COP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/co.svg"],
            ["name" => "Comoros", "dial_code" => "+269", "iso_code" => "KM", "currency_code" => "KMF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/km.svg"],
            ["name" => "Congo", "dial_code" => "+242", "iso_code" => "CG", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cg.svg"],
            ["name" => "Cook Islands", "dial_code" => "+682", "iso_code" => "CK", "currency_code" => "NZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ck.svg"],
            ["name" => "Costa Rica", "dial_code" => "+506", "iso_code" => "CR", "currency_code" => "CRC", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cr.svg"],
            ["name" => "Croatia", "dial_code" => "+385", "iso_code" => "HR", "currency_code" => "HRK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/hr.svg"],
            ["name" => "Cuba", "dial_code" => "+53", "iso_code" => "CU", "currency_code" => "CUP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cu.svg"],
            ["name" => "Cyprus", "dial_code" => "+357", "iso_code" => "CY", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cy.svg"],
            ["name" => "Czech Republic", "dial_code" => "+420", "iso_code" => "CZ", "currency_code" => "CZK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cz.svg"],
            ["name" => "Democratic Republic of the Congo", "dial_code" => "+243", "iso_code" => "CD", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/cd.svg"],
            ["name" => "Denmark", "dial_code" => "+45", "iso_code" => "DK", "currency_code" => "DKK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/dk.svg"],
            ["name" => "Djibouti", "dial_code" => "+253", "iso_code" => "DJ", "currency_code" => "DJF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/dj.svg"],
            ["name" => "Dominica", "dial_code" => "+1767", "iso_code" => "DM", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/dm.svg"],
            ["name" => "Dominican Republic", "dial_code" => "+1849", "iso_code" => "DO", "currency_code" => "DOP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/do.svg"],
            ["name" => "Ecuador", "dial_code" => "+593", "iso_code" => "EC", "currency_code" => "ECS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ec.svg"],
            ["name" => "Egypt", "dial_code" => "+20", "iso_code" => "EG", "currency_code" => "EGP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/eg.svg"],
            ["name" => "El Salvador", "dial_code" => "+503", "iso_code" => "SV", "currency_code" => "SVC", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sv.svg"],
            ["name" => "Equatorial Guinea", "dial_code" => "+240", "iso_code" => "GQ", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gq.svg"],
            ["name" => "Eritrea", "dial_code" => "+291", "iso_code" => "ER", "currency_code" => "ERN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/er.svg"],
            ["name" => "Estonia", "dial_code" => "+372", "iso_code" => "EE", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ee.svg"],
            ["name" => "Eswatini", "dial_code" => "+268", "iso_code" => "SZ", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sz.svg"],
            ["name" => "Ethiopia", "dial_code" => "+251", "iso_code" => "ET", "currency_code" => "ETB", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/et.svg"],
            ["name" => "Falkland Islands (Malvinas)", "dial_code" => "+500", "iso_code" => "FK", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fk.svg"],
            ["name" => "Faroe Islands", "dial_code" => "+298", "iso_code" => "FO", "currency_code" => "DKK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fo.svg"],
            ["name" => "Fiji", "dial_code" => "+679", "iso_code" => "FJ", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fj.svg"],
            ["name" => "Finland", "dial_code" => "+358", "iso_code" => "FI", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fi.svg"],
            ["name" => "France", "dial_code" => "+33", "iso_code" => "FR", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fr.svg"],
            ["name" => "French Guiana", "dial_code" => "+594", "iso_code" => "GF", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gf.svg"],
            ["name" => "French Polynesia", "dial_code" => "+689", "iso_code" => "PF", "currency_code" => "XPF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pf.svg"],
            ["name" => "Gabon", "dial_code" => "+241", "iso_code" => "GA", "currency_code" => "XAF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ga.svg"],
            ["name" => "Gambia", "dial_code" => "+220", "iso_code" => "GM", "currency_code" => "GMD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gm.svg"],
            ["name" => "Georgia", "dial_code" => "+995", "iso_code" => "GE", "currency_code" => "GEL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ge.svg"],
            ["name" => "Germany", "dial_code" => "+49", "iso_code" => "DE", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/de.svg"],
            ["name" => "Ghana", "dial_code" => "+233", "iso_code" => "GH", "currency_code" => "GHS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gh.svg"],
            ["name" => "Gibraltar", "dial_code" => "+350", "iso_code" => "GI", "currency_code" => "GIP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gi.svg"],
            ["name" => "Greece", "dial_code" => "+30", "iso_code" => "GR", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gr.svg"],
            ["name" => "Greenland", "dial_code" => "+299", "iso_code" => "GL", "currency_code" => "DKK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gl.svg"],
            ["name" => "Grenada", "dial_code" => "+1473", "iso_code" => "GD", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gd.svg"],
            ["name" => "Guadeloupe", "dial_code" => "+590", "iso_code" => "GP", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gp.svg"],
            ["name" => "Guam", "dial_code" => "+1671", "iso_code" => "GU", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gu.svg"],
            ["name" => "Guatemala", "dial_code" => "+502", "iso_code" => "GT", "currency_code" => "QTQ", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gt.svg"],
            ["name" => "Guernsey", "dial_code" => "+44", "iso_code" => "GG", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gg.svg"],
            ["name" => "Guinea", "dial_code" => "+224", "iso_code" => "GN", "currency_code" => "GNF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gn.svg"],
            ["name" => "Guinea-Bissau", "dial_code" => "+245", "iso_code" => "GW", "currency_code" => "CFA", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gw.svg"],
            ["name" => "Guyana", "dial_code" => "+592", "iso_code" => "GY", "currency_code" => "GYD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gy.svg"],
            ["name" => "Haiti", "dial_code" => "+509", "iso_code" => "HT", "currency_code" => "HTG", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ht.svg"],
            ["name" => "Holy See (Vatican City State)", "dial_code" => "+379", "iso_code" => "VA", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/va.svg"],
            ["name" => "Honduras", "dial_code" => "+504", "iso_code" => "HN", "currency_code" => "HNL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/hn.svg"],
            ["name" => "Hong Kong", "dial_code" => "+852", "iso_code" => "HK", "currency_code" => "HKD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/hk.svg"],
            ["name" => "Hungary", "dial_code" => "+36", "iso_code" => "HU", "currency_code" => "HUF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/hu.svg"],
            ["name" => "Iceland", "dial_code" => "+354", "iso_code" => "IS", "currency_code" => "ISK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/is.svg"],
            ["name" => "India", "dial_code" => "+91", "iso_code" => "IN", "currency_code" => "INR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/in.svg"],
            ["name" => "Indonesia", "dial_code" => "+62", "iso_code" => "ID", "currency_code" => "IDR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/id.svg"],
            ["name" => "Iran", "dial_code" => "+98", "iso_code" => "IR", "currency_code" => "IRR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ir.svg"],
            ["name" => "Iraq", "dial_code" => "+964", "iso_code" => "IQ", "currency_code" => "IQD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/iq.svg"],
            ["name" => "Ireland", "dial_code" => "+353", "iso_code" => "IE", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ie.svg"],
            ["name" => "Isle of Man", "dial_code" => "+44", "iso_code" => "IM", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/im.svg"],
            ["name" => "Israel", "dial_code" => "+972", "iso_code" => "IL", "currency_code" => "ILS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/il.svg"],
            ["name" => "Italy", "dial_code" => "+39", "iso_code" => "IT", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/it.svg"],
            ["name" => "Ivory Coast / Cote d'Ivoire", "dial_code" => "+225", "iso_code" => "CI", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ci.svg"],
            ["name" => "Jamaica", "dial_code" => "+1876", "iso_code" => "JM", "currency_code" => "JMD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/jm.svg"],
            ["name" => "Japan", "dial_code" => "+81", "iso_code" => "JP", "currency_code" => "JPY", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/jp.svg"],
            ["name" => "Jersey", "dial_code" => "+44", "iso_code" => "JE", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/je.svg"],
            ["name" => "Jordan", "dial_code" => "+962", "iso_code" => "JO", "currency_code" => "JOD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/jo.svg"],
            ["name" => "Kazakhstan", "dial_code" => "+77", "iso_code" => "KZ", "currency_code" => "KZT", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kz.svg"],
            ["name" => "Kenya", "dial_code" => "+254", "iso_code" => "KE", "currency_code" => "KES", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ke.svg"],
            ["name" => "Kiribati", "dial_code" => "+686", "iso_code" => "KI", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ki.svg"],
            ["name" => "Korea, Democratic People's Republic of Korea", "dial_code" => "+850", "iso_code" => "KP", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kp.svg"],
            ["name" => "Korea, Republic of South Korea", "dial_code" => "+82", "iso_code" => "KR", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kr.svg"],
            ["name" => "Kosovo", "dial_code" => "+383", "iso_code" => "XK", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/xk.svg"],
            ["name" => "Kuwait", "dial_code" => "+965", "iso_code" => "KW", "currency_code" => "KWD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kw.svg"],
            ["name" => "Kyrgyzstan", "dial_code" => "+996", "iso_code" => "KG", "currency_code" => "KGS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kg.svg"],
            ["name" => "Laos", "dial_code" => "+856", "iso_code" => "LA", "currency_code" => "LAK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/la.svg"],
            ["name" => "Latvia", "dial_code" => "+371", "iso_code" => "LV", "currency_code" => "LVL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lv.svg"],
            ["name" => "Lebanon", "dial_code" => "+961", "iso_code" => "LB", "currency_code" => "LBP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lb.svg"],
            ["name" => "Lesotho", "dial_code" => "+266", "iso_code" => "LS", "currency_code" => "LSL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ls.svg"],
            ["name" => "Liberia", "dial_code" => "+231", "iso_code" => "LR", "currency_code" => "LRD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lr.svg"],
            ["name" => "Libya", "dial_code" => "+218", "iso_code" => "LY", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ly.svg"],
            ["name" => "Liechtenstein", "dial_code" => "+423", "iso_code" => "LI", "currency_code" => "CHF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/li.svg"],
            ["name" => "Lithuania", "dial_code" => "+370", "iso_code" => "LT", "currency_code" => "LTL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lt.svg"],
            ["name" => "Luxembourg", "dial_code" => "+352", "iso_code" => "LU", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lu.svg"],
            ["name" => "Macau", "dial_code" => "+853", "iso_code" => "MO", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mo.svg"],
            ["name" => "Madagascar", "dial_code" => "+261", "iso_code" => "MG", "currency_code" => "MGF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mg.svg"],
            ["name" => "Malawi", "dial_code" => "+265", "iso_code" => "MW", "currency_code" => "MWK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mw.svg"],
            ["name" => "Malaysia", "dial_code" => "+60", "iso_code" => "MY", "currency_code" => "MYR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/my.svg"],
            ["name" => "Maldives", "dial_code" => "+960", "iso_code" => "MV", "currency_code" => "MVR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mv.svg"],
            ["name" => "Mali", "dial_code" => "+223", "iso_code" => "ML", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ml.svg"],
            ["name" => "Malta", "dial_code" => "+356", "iso_code" => "MT", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mt.svg"],
            ["name" => "Marshall Islands", "dial_code" => "+692", "iso_code" => "MH", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mh.svg"],
            ["name" => "Martinique", "dial_code" => "+596", "iso_code" => "MQ", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mq.svg"],
            ["name" => "Mauritania", "dial_code" => "+222", "iso_code" => "MR", "currency_code" => "MRO", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mr.svg"],
            ["name" => "Mauritius", "dial_code" => "+230", "iso_code" => "MU", "currency_code" => "MUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mu.svg"],
            ["name" => "Mayotte", "dial_code" => "+262", "iso_code" => "YT", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/yt.svg"],
            ["name" => "Mexico", "dial_code" => "+52", "iso_code" => "MX", "currency_code" => "MXN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mx.svg"],
            ["name" => "Micronesia, Federated States of Micronesia", "dial_code" => "+691", "iso_code" => "FM", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/fm.svg"],
            ["name" => "Moldova", "dial_code" => "+373", "iso_code" => "MD", "currency_code" => "MDL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/md.svg"],
            ["name" => "Monaco", "dial_code" => "+377", "iso_code" => "MC", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mc.svg"],
            ["name" => "Mongolia", "dial_code" => "+976", "iso_code" => "MN", "currency_code" => "MNT", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mn.svg"],
            ["name" => "Montenegro", "dial_code" => "+382", "iso_code" => "ME", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/me.svg"],
            ["name" => "Montserrat", "dial_code" => "+1664", "iso_code" => "MS", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ms.svg"],
            ["name" => "Morocco", "dial_code" => "+212", "iso_code" => "MA", "currency_code" => "MAD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ma.svg"],
            ["name" => "Mozambique", "dial_code" => "+258", "iso_code" => "MZ", "currency_code" => "MZN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mz.svg"],
            ["name" => "Myanmar", "dial_code" => "+95", "iso_code" => "MM", "currency_code" => "MMR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mm.svg"],
            ["name" => "Namibia", "dial_code" => "+264", "iso_code" => "NA", "currency_code" => "NAD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/na.svg"],
            ["name" => "Nauru", "dial_code" => "+674", "iso_code" => "NR", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nr.svg"],
            ["name" => "Nepal", "dial_code" => "+977", "iso_code" => "NP", "currency_code" => "NPR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/np.svg"],
            ["name" => "Netherlands", "dial_code" => "+31", "iso_code" => "NL", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nl.svg"],
            ["name" => "Netherlands Antilles", "dial_code" => "+599", "iso_code" => "AN", "currency_code" => "ANG", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/an.svg"],
            ["name" => "New Caledonia", "dial_code" => "+687", "iso_code" => "NC", "currency_code" => "XPF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nc.svg"],
            ["name" => "New Zealand", "dial_code" => "+64", "iso_code" => "NZ", "currency_code" => "NZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nz.svg"],
            ["name" => "Nicaragua", "dial_code" => "+505", "iso_code" => "NI", "currency_code" => "NIO", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ni.svg"],
            ["name" => "Niger", "dial_code" => "+227", "iso_code" => "NE", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ne.svg"],
            ["name" => "Nigeria", "dial_code" => "+234", "iso_code" => "NG", "currency_code" => "NGN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ng.svg"],
            ["name" => "Niue", "dial_code" => "+683", "iso_code" => "NU", "currency_code" => "NZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nu.svg"],
            ["name" => "Norfolk Island", "dial_code" => "+672", "iso_code" => "NF", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/nf.svg"],
            ["name" => "North Macedonia", "dial_code" => "+389", "iso_code" => "MK", "currency_code" => "MKD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mk.svg"],
            ["name" => "Northern Mariana Islands", "dial_code" => "+1670", "iso_code" => "MP", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mp.svg"],
            ["name" => "Norway", "dial_code" => "+47", "iso_code" => "NO", "currency_code" => "NOK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/no.svg"],
            ["name" => "Oman", "dial_code" => "+968", "iso_code" => "OM", "currency_code" => "OMR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/om.svg"],
            ["name" => "Pakistan", "dial_code" => "+92", "iso_code" => "PK", "currency_code" => "PKR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pk.svg"],
            ["name" => "Palau", "dial_code" => "+680", "iso_code" => "PW", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pw.svg"],
            ["name" => "Palestine", "dial_code" => "+970", "iso_code" => "PS", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ps.svg"],
            ["name" => "Panama", "dial_code" => "+507", "iso_code" => "PA", "currency_code" => "PAB", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pa.svg"],
            ["name" => "Papua New Guinea", "dial_code" => "+675", "iso_code" => "PG", "currency_code" => "PGK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pg.svg"],
            ["name" => "Paraguay", "dial_code" => "+595", "iso_code" => "PY", "currency_code" => "PYG", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/py.svg"],
            ["name" => "Peru", "dial_code" => "+51", "iso_code" => "PE", "currency_code" => "PEN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pe.svg"],
            ["name" => "Philippines", "dial_code" => "+63", "iso_code" => "PH", "currency_code" => "PHP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ph.svg"],
            ["name" => "Pitcairn", "dial_code" => "+872", "iso_code" => "PN", "currency_code" => "NZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pn.svg"],
            ["name" => "Poland", "dial_code" => "+48", "iso_code" => "PL", "currency_code" => "PLN", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pl.svg"],
            ["name" => "Portugal", "dial_code" => "+351", "iso_code" => "PT", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pt.svg"],
            ["name" => "Puerto Rico", "dial_code" => "+1939", "iso_code" => "PR", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pr.svg"],
            ["name" => "Qatar", "dial_code" => "+974", "iso_code" => "QA", "currency_code" => "QAR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/qa.svg"],
            ["name" => "Reunion", "dial_code" => "+262", "iso_code" => "RE", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/re.svg"],
            ["name" => "Romania", "dial_code" => "+40", "iso_code" => "RO", "currency_code" => "RON", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ro.svg"],
            ["name" => "Russia", "dial_code" => "+7", "iso_code" => "RU", "currency_code" => "RUB", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ru.svg"],
            ["name" => "Rwanda", "dial_code" => "+250", "iso_code" => "RW", "currency_code" => "RWF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/rw.svg"],
            ["name" => "Saint Barthelemy", "dial_code" => "+590", "iso_code" => "BL", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/bl.svg"],
            ["name" => "Saint Helena, Ascension and Tristan Da Cunha", "dial_code" => "+290", "iso_code" => "SH", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sh.svg"],
            ["name" => "Saint Kitts and Nevis", "dial_code" => "+1869", "iso_code" => "KN", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/kn.svg"],
            ["name" => "Saint Lucia", "dial_code" => "+1758", "iso_code" => "LC", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lc.svg"],
            ["name" => "Saint Martin", "dial_code" => "+590", "iso_code" => "MF", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/mf.svg"],
            ["name" => "Saint Pierre and Miquelon", "dial_code" => "+508", "iso_code" => "PM", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/pm.svg"],
            ["name" => "Saint Vincent and the Grenadines", "dial_code" => "+1784", "iso_code" => "VC", "currency_code" => "XCD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/vc.svg"],
            ["name" => "Samoa", "dial_code" => "+685", "iso_code" => "WS", "currency_code" => "WST", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ws.svg"],
            ["name" => "San Marino", "dial_code" => "+378", "iso_code" => "SM", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sm.svg"],
            ["name" => "Sao Tome and Principe", "dial_code" => "+239", "iso_code" => "ST", "currency_code" => "STD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/st.svg"],
            ["name" => "Saudi Arabia", "dial_code" => "+966", "iso_code" => "SA", "currency_code" => "SAR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sa.svg"],
            ["name" => "Senegal", "dial_code" => "+221", "iso_code" => "SN", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sn.svg"],
            ["name" => "Serbia", "dial_code" => "+381", "iso_code" => "RS", "currency_code" => "RSD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/rs.svg"],
            ["name" => "Seychelles", "dial_code" => "+248", "iso_code" => "SC", "currency_code" => "SCR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sc.svg"],
            ["name" => "Sierra Leone", "dial_code" => "+232", "iso_code" => "SL", "currency_code" => "SLL", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sl.svg"],
            ["name" => "Singapore", "dial_code" => "+65", "iso_code" => "SG", "currency_code" => "SGD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sg.svg"],
            ["name" => "Sint Maarten", "dial_code" => "+1721", "iso_code" => "SX", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sx.svg"],
            ["name" => "Slovakia", "dial_code" => "+421", "iso_code" => "SK", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sk.svg"],
            ["name" => "Slovenia", "dial_code" => "+386", "iso_code" => "SI", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/si.svg"],
            ["name" => "Solomon Islands", "dial_code" => "+677", "iso_code" => "SB", "currency_code" => "SBD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sb.svg"],
            ["name" => "Somalia", "dial_code" => "+252", "iso_code" => "SO", "currency_code" => "SOS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/so.svg"],
            ["name" => "South Africa", "dial_code" => "+27", "iso_code" => "ZA", "currency_code" => "ZAR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/za.svg"],
            ["name" => "South Georgia and the South Sandwich Islands", "dial_code" => "+500", "iso_code" => "GS", "currency_code" => "GBP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gs.svg"],
            ["name" => "South Sudan", "dial_code" => "+211", "iso_code" => "SS", "currency_code" => "SSP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ss.svg"],
            ["name" => "Spain", "dial_code" => "+34", "iso_code" => "ES", "currency_code" => "EUR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/es.svg"],
            ["name" => "Sri Lanka", "dial_code" => "+94", "iso_code" => "LK", "currency_code" => "LKR", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/lk.svg"],
            ["name" => "Sudan", "dial_code" => "+249", "iso_code" => "SD", "currency_code" => "SDG", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sd.svg"],
            ["name" => "Suriname", "dial_code" => "+597", "iso_code" => "SR", "currency_code" => "SRD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sr.svg"],
            ["name" => "Svalbard and Jan Mayen", "dial_code" => "+47", "iso_code" => "SJ", "currency_code" => "NOK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sj.svg"],
            ["name" => "Sweden", "dial_code" => "+46", "iso_code" => "SE", "currency_code" => "SEK", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/se.svg"],
            ["name" => "Switzerland", "dial_code" => "+41", "iso_code" => "CH", "currency_code" => "CHF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ch.svg"],
            ["name" => "Syrian Arab Republic", "dial_code" => "+963", "iso_code" => "SY", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/sy.svg"],
            ["name" => "Taiwan", "dial_code" => "+886", "iso_code" => "TW", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tw.svg"],
            ["name" => "Tajikistan", "dial_code" => "+992", "iso_code" => "TJ", "currency_code" => "TJS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tj.svg"],
            ["name" => "Tanzania, United Republic of Tanzania", "dial_code" => "+255", "iso_code" => "TZ", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tz.svg"],
            ["name" => "Thailand", "dial_code" => "+66", "iso_code" => "TH", "currency_code" => "THB", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/th.svg"],
            ["name" => "Timor-Leste", "dial_code" => "+670", "iso_code" => "TL", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tl.svg"],
            ["name" => "Togo", "dial_code" => "+228", "iso_code" => "TG", "currency_code" => "XOF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tg.svg"],
            ["name" => "Tokelau", "dial_code" => "+690", "iso_code" => "TK", "currency_code" => "NZD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tk.svg"],
            ["name" => "Tonga", "dial_code" => "+676", "iso_code" => "TO", "currency_code" => "TOP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/to.svg"],
            ["name" => "Trinidad and Tobago", "dial_code" => "+1868", "iso_code" => "TT", "currency_code" => "TTD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tt.svg"],
            ["name" => "Tunisia", "dial_code" => "+216", "iso_code" => "TN", "currency_code" => "TND", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tn.svg"],
            ["name" => "Turkey", "dial_code" => "+90", "iso_code" => "TR", "currency_code" => "TRY", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tr.svg"],
            ["name" => "Turkmenistan", "dial_code" => "+993", "iso_code" => "TM", "currency_code" => "TMT", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tm.svg"],
            ["name" => "Turks and Caicos Islands", "dial_code" => "+1649", "iso_code" => "TC", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tc.svg"],
            ["name" => "Tuvalu", "dial_code" => "+688", "iso_code" => "TV", "currency_code" => "AUD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/tv.svg"],
            ["name" => "Uganda", "dial_code" => "+256", "iso_code" => "UG", "currency_code" => "UGX", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ug.svg"],
            ["name" => "Ukraine", "dial_code" => "+380", "iso_code" => "UA", "currency_code" => "UAH", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ua.svg"],
            ["name" => "United Arab Emirates", "dial_code" => "+971", "iso_code" => "AE", "currency_code" => "AED", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ae.svg"],
            ["name" => "United Kingdom", "dial_code" => "+44", "iso_code" => "GB", "currency_code" => "GBP", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/gb.svg"],
            ["name" => "United States", "dial_code" => "+1", "iso_code" => "US", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/us.svg"],
            ["name" => "United States Minor Outlying Islands", "dial_code" => "+246", "iso_code" => "UMI", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/umi.svg"],
            ["name" => "Uruguay", "dial_code" => "+598", "iso_code" => "UY", "currency_code" => "UYU", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/uy.svg"],
            ["name" => "Uzbekistan", "dial_code" => "+998", "iso_code" => "UZ", "currency_code" => "UZS", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/uz.svg"],
            ["name" => "Vanuatu", "dial_code" => "+678", "iso_code" => "VU", "currency_code" => "VUV", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/vu.svg"],
            ["name" => "Venezuela, Bolivarian Republic of Venezuela", "dial_code" => "+58", "iso_code" => "VE", "currency_code" => null, "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ve.svg"],
            ["name" => "Vietnam", "dial_code" => "+84", "iso_code" => "VN", "currency_code" => "VND", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/vn.svg"],
            ["name" => "Virgin Islands, British", "dial_code" => "+1284", "iso_code" => "VG", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/vg.svg"],
            ["name" => "Virgin Islands, U.S.", "dial_code" => "+1340", "iso_code" => "VI", "currency_code" => "USD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/vi.svg"],
            ["name" => "Wallis and Futuna", "dial_code" => "+681", "iso_code" => "WF", "currency_code" => "XPF", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/wf.svg"],
            ["name" => "Yemen", "dial_code" => "+967", "iso_code" => "YE", "currency_code" => "YER", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/ye.svg"],
            ["name" => "Zambia", "dial_code" => "+260", "iso_code" => "ZM", "currency_code" => "ZMW", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/zm.svg"],
            ["name" => "Zimbabwe", "dial_code" => "+263", "iso_code" => "ZW", "currency_code" => "ZWD", "flag" => "https://cdn.kcak11.com/CountryFlags/countries/zw.svg"],
        ];

        return $code
            ? collect($countries)->where('iso_code', $code)->first()
            : $countries;
    }
}